### ISSUE TITLE
User-ID updates are slow

### ISSUE THREAD

**Issue by Ay4shi** [PaloAltoNetworks/pandevice#130] opened 2018-09-24 11:27 UTC
I've been trying to use this Library to manage my ip-user mappings. It works but at a cost :

Adding 1300 users takes 25 minutes with this Library and less than one second with the XML API.

No need to say that I'll go back to the old fashioned XML way.

**Comment by btorresgil** [comment] 2018-09-24 13:44
Hello,

We have customers using this library to batch thousands of user updates in production every few seconds, so I’m certain it is capable of what you describe.

Can you share your code so we can help determine what is causing the bottle neck?

Thanks!

**Comment by btorresgil** [comment] 2018-09-29 17:13
I'd love to help you further with this, so please let us know what your code looks like so we can find where the slowdown is.

In the meantime, I'll venture a guess as to the cause.  When you use the `login()` and `logout()` methods it causes an immediate API call.  So if you call `login()` for every one of the 1300 users, then this would take a very long time to complete because each API call takes several milliseconds.  This is likely what's happening since you state 1300 users takes 25 minutes, and that means about 0.86 seconds per user.

A more efficient way to handle these logins is to batch them into one API request.  So, instead of this:

   fw.userid.login('user1', '10.0.5.1')
   fw.userid.login('user2', '10.0.5.2')

Do this:

    fw.userid.batch_start()
    fw.userid.login('user1', '10.0.5.1')
    fw.userid.login('user2', '10.0.5.2')
    fw.userid.batch_end()

That way, instead of 2 API calls (one for user1 and one for user2), there will only be 1 API call containing both users.  You can likely fit all 1300 users into a single API call, though you might want to experiment with batching them into groups of a few hundred at a time.

Hope that helps!  Let me know if my suggestion fixes the issue, or if there is something else going on.  Thanks!

**Comment by btorresgil** [comment] 2018-09-29 17:14
Also, here's the docs on the User-ID batching methods:  https://pandevice.readthedocs.io/en/latest/module-userid.html#pandevice.userid.UserId.batch_end

**Comment by btorresgil** [comment] 2018-11-19 23:44
Going to close this out since it doesn't seem to be an issue.  Check my solution above to scale User-ID API calls.  Feel free to comment if that hasn't solved the issue.

**Closed by btorresgil** 2018-11-19 23:44 UTC
